global:
  hosts:
    domain: local.gitlab.example.com
    externalIP: 192.168.49.2 # Replace with your minikube IP

  ingress:
    configureCertmanager: false
    tls:
      enabled: false

  edition: ce

nginx-ingress:
  enabled: true
  controller:
    replicaCount: 1
    service:
      type: NodePort
      nodePorts:
        http: 30080
        https: 30443

certmanager:
  install: false

gitlab:
  webservice:
    replicas: 1
    minReplicas: 1
    maxReplicas: 1

  sidekiq:
    replicas: 1

  toolbox:
    enabled: true

  migrations:
    enabled: true

  gitaly:
    replicas: 1

  kas:
    enabled: true

  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1

  gitlab-exporter:
    enabled: true

  prometheus:
    install: true

  minio:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
    persistence:
      size: 1Gi

  redis:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m

  postgresql:
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
    image:
      tag: 14.10.0

gitlab-runner:
  install: false
