global:
  edition: ce
  hosts:
    domain: localhost
    externalIP: 192.168.49.2 
    https: false
  ingress:
    configureCertmanager: false
    class: nginx
    annotations: {}

nginx-ingress:
  enabled: true
  controller:
    service:
      type: NodePort

gitlab:
  webservice:
    replicas: 1

redis:
  install: true

postgresql:
  install: true
