# Global settings
global:
  host: localhost  # Change to your domain

# GitLab settings
gitlab:
  webservice:
    replicas: 1  # Set to 1 to disable HA
    service:
      enabled: true
      type: ClusterIP
      ports:
        - name: http
          port: 80
    env:
      GITLAB_ROOT_PASSWORD: "yourStrongPassword"

  serviceAccount:
    create: true
    name: ""      # Leave empty to use the default name
    annotations: {}

  ingress:
    enabled: true
    path: /
    pathType: Prefix
    annotations:
    tls:
      enabled: false
    hosts:
      - host: localhost
        paths:
          - path: /

# Autoscaling settings
autoscaling:
  enabled: false  # Disable autoscaling for non-HA
  minReplicas: 1  # Set to 1 for single instance
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

# PostgreSQL settings
postgresql:
  enabled: true
  auth:
    username: gitlab
    password: gitlabpassword  # Use a Secret for production
    database: gitlabhq_production
  primary:
    persistence:
      enabled: true
      size: 8Gi

# Additional configurations
resources:
  requests:
    cpu: "1"
    memory: "1Gi"  # Increase memory for production
  limits:
    cpu: "2"
    memory: "4Gi"
