# Global settings
global:
  host: localhost  # Change to your domain
  ingress:
    enabled: true
    annotations: {}
    pathType: Prefix
    paths:
      - /
    tls:
      enabled: true
      secretName: gitlab-tls  # Use a real TLS secret

# GitLab settings
gitlab:
  webservice:
    replicas: 2  # Use at least 2 for HA
    service:
      enabled: true
      type: ClusterIP
      ports:
        - name: http
          port: 80
        - name: https
          port: 443

  serviceAccount:
    create: true
    name: ""      # Leave empty to use the default name
    annotations: {}

  ingress:
    enabled: true
    path: /
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      enabled: true
      secretName: gitlab-tls
    hosts:
      - host: localhost
        paths:
          - path: /

# Autoscaling settings
autoscaling:
  enabled: true
  minReplicas: 2  # At least 2 for HA
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# PostgreSQL settings
postgresql:
  enabled: true
  image:
    tag: "16.2"  # Explicitly set the image tag
  postgresqlUsername: gitlab
  postgresqlPassword: gitlabpassword  # Change to a secure password or use a Secret
  postgresqlDatabase: gitlabhq_production
  service:
    enabled: true
    type: ClusterIP

# Additional configurations
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"  # Increase memory for production
  limits:
    cpu: "2"
    memory: "4Gi"
