# Global settings
global:
  host: localhost  # Change to your domain

# GitLab settings
gitlab:
  webservice:
    replicas: 1  # Set to 1 to disable HA
    service:
      enabled: true
      type: ClusterIP
      ports:
        - name: http
          port: 80
    env:
      # This variable is directly used by GitLab Omnibus to set the initial root password
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = 'your-new-strong-password'
      # The GITLAB_ROOT_PASSWORD variable you had previously is not a standard GitLab Omnibus configuration.
      # You can remove it or keep it if you have custom logic that uses it.

  serviceAccount:
    create: true
    name: ""      # Leave empty to use the default name
    annotations: {}

  ingress:
    enabled: true
    path: /
    pathType: Prefix
    annotations: {}
    tls:
      enabled: false
    hosts:
      - host: localhost
        paths:
          - path: /

  externalUrl: "http://localhost"
  rootPasswordSecret: "gitlab-root-password"

# Autoscaling settings
autoscaling:
  enabled: false  # Disable autoscaling for non-HA
  minReplicas: 1  # Set to 1 for single instance
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

# PostgreSQL settings
postgresql:
  enabled: true
  auth:
    username: gitlab
    password: gitlabpassword
    database: gitlabhq_production
  primary:
    persistence:
      enabled: true
      size: 8Gi

# Additional configurations
resources:
  requests:
    cpu: "1"
    memory: "1Gi"  # Increase memory for production
  limits:
    cpu: "2"
    memory: "4Gi"
