apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab.fullname" . }}
  labels:
    app: {{ include "gitlab.name" . }}
    chart: {{ include "gitlab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceAccountName: {{ include "gitlab.serviceAccountName" . }}
  replicas: {{ .Values.gitlab.webservice.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "gitlab.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "gitlab.name" . }}
    spec:
      containers:
        - name: gitlab
          image: "gitlab/gitlab-ce:{{ .Chart.AppVersion }}"
          ports:
            - containerPort: 80
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url '{{ .Values.gitlab.externalUrl }}'
                gitlab_rails['db_adapter'] = 'postgresql'
                gitlab_rails['db_encoding'] = 'utf8'
                gitlab_rails['db_host'] = 'gitlab-postgresql'
                gitlab_rails['db_port'] = '5432'
                gitlab_rails['db_username'] = '{{ .Values.postgresql.auth.username }}'
                gitlab_rails['db_password'] = '{{ .Values.postgresql.auth.password }}'
                gitlab_rails['db_database'] = '{{ .Values.postgresql.auth.database }}'
            - name: GITLAB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gitlab.rootPasswordSecret }}
                  key: password
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
