{{- if .Values.gitlab.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gitlab.fullname" . }}
  annotations:
{{- toYaml .Values.gitlab.ingress.annotations | nindent 4 }}
spec:
  tls:
  {{- if .Values.gitlab.ingress.tls.enabled }}
    - hosts:
        {{- range .Values.gitlab.ingress.hosts }}
        - {{ .host }}
        {{- end }}
      secretName: {{ .Values.gitlab.ingress.tls.secretName }}
  {{- end }}
  rules:
  {{- range .Values.gitlab.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ $.Values.gitlab.ingress.pathType }}
            backend:
              service:
                name: {{ include "gitlab.fullname" $ }}
                port:
                  number: 80
          {{- end }}
  {{- end }}
{{- end }}
