apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab.fullname" . }}-postgresql
  labels:
    app: {{ include "gitlab.name" . }}-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "gitlab.name" . }}-postgresql
  template:
    metadata:
      labels:
        app: {{ include "gitlab.name" . }}-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:{{ .Values.postgresql.image.tag }}  # Use a placeholder
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresqlDatabase }}
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
