apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab.fullname" . }}-postgresql
  labels:
    app: {{ include "gitlab.name" . }}-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "gitlab.name" . }}-postgresql
  template:
    metadata:
      labels:
        app: {{ include "gitlab.name" . }}-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:{{ .Values.postgresql.image.tag }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresqlDatabase }}
          ports:
            - containerPort: 5432
          service:
            enabled: true
            type: ClusterIP
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
# Values for the PostgreSQL deployment
postgresql:
  enabled: true
  image:
    tag: "16.2"  # Add this line, or your preferred version
  postgresqlUsername: gitlab
  postgresqlPassword: gitlabpassword  # Change to a secure password
  postgresqlDatabase: gitlabhq_production
