apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab.fullname" . }}
spec:
  type: {{ .Values.gitlab.webservice.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: {{ include "gitlab.name" . }}
