apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab.fullname" . }}
  labels:
    app: {{ include "gitlab.name" . }}
    chart: {{ include "gitlab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.gitlab.webservice.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "gitlab.name" . }}
