apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if .Values.gitlab.serviceAccount.name }}{{ .Values.gitlab.serviceAccount.name }}{{ else }}{{ include "gitlab.fullname" . }}-sa{{ end }}
  labels:
    app: {{ include "gitlab.name" . }}
    chart: {{ include "gitlab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.gitlab.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.gitlab.serviceAccount.annotations | nindent 4 }}
{{- end }}
